### ISSUE TITLE
Can't run 1.8.0

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#174]
```
andreas@thinkpad:~/% java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
This is on Debian. I have the package "openjfx" installed. I get the following errors:
```
andreas@thinkpad:~/src/CorefAnnotator/target/% java -jar CorefAnnotator-1.8.0-full.jar        
17:43:04.117 TRACE d.u.i.c.a.Annotator annotator.Annotator.<init> - Application startup. Version 1.8.0
Exception in thread "AWT-EventQueue-1" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at de.unistuttgart.ims.coref.annotator.Annotator.<init>(Annotator.java:115)           
        at de.unistuttgart.ims.coref.annotator.Annotator$1.run(Annotator.java:102)            
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)                  
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)                         
        at java.awt.EventQueue.access$500(EventQueue.java:97)                                 
        at java.awt.EventQueue$3.run(EventQueue.java:709)                                     
        at java.awt.EventQueue$3.run(EventQueue.java:703)                                     
        at java.security.AccessController.doPrivileged(Native Method)                         
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)                             
        at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)            
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)  
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)     
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)  
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)              
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)               
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)                      
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel                      
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)                         
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                              
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)                      
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)                              
        ... 17 more
```
Do I have the right Java versions etc.?

**Comment by nilsreiter** [comment]
That's odd. I have the exact same configuration (Debian, openjdk 1.8.0_181-8u181-b13-1~deb9u1-b13) and I got the same error message at first -- but after installing `openjfx` via apt-get it worked fine. Maybe a path issue?

**Comment by andreasvc** [comment]
Good to know it should work with these versions. Do you set any Java-related paths in .bashrc perhaps? I tried upgrading to Java 11 but same error.

**Comment by nilsreiter** [comment]
No I didn't. It's a debian (stretch) machine I rarely use, so it's pretty much in the default settings. 

@pagelj: What Linux are you running and does it work for you?

**Comment by andreasvc** [comment]
Ah, I'm on Debian testing. I guess I could try installing Oracle Java/JavaFX next. I have the impression that the problem with openjfx is that it's a separate package and openjdk doesn't know where to find it, while JavaFX seems to be included with Oracle JDK.

BTW I also had Windows users report that 1.8.0 didn't run for them, but don't know the details. It would be good to mention the recommended Java version in the README.

**Comment by nilsreiter** [comment]
If you could get a windows user to run it in the terminal and send me the output, that would be great. I tested with Windows 10 and Oracle Java 1.8.

The minimal requirement is Java 1.8, but I don't test other versions extensively. I'm developing on Oracle JDK, but I try to get it to run on OpenJDK as well ... Yes, that should be in the README 👍

**Comment by pagelj** [comment]
I am testing it on Arch and am able to run it with the Arch java-openjfx package installed

**Comment by andreasvc** [comment]
OK I finally managed to get 1.8.0 to run. Here are my observations:

- OpenJDK does not come with JavaFX, so it needs to be installed separately
- However, Debian testing/buster does not ship openjfx 8, and openfx 11 is not found by openjdk 11 for some mysterious reason.
- Oracle Java 11 no longer includes JavaFX: https://blog.codefx.org/java/java-11-migration-guide/#Removal-Of-Deprecated-APIs-and-JavaFX
- Therefore, to use JavaFX with Java 11, openfx needs to be installed separately: https://openjfx.io/openjfx-docs/#install-javafx
- Oracle Java 8 does include JavaFX, so this version has the best chance of working out of the box.

After selling my soul to Oracle I was able to obtain Java 8 and packaged it following https://wiki.debian.org/JavaPackage
After removing all other JRE/JDK versions, CorefAnnotator 1.8.0 finally works.

**Comment by nilsreiter** [comment]
Thanks for tracking this! (and sorry about your soul ...)

I'll try to package javafx into the "full" jar, just like the others.

**Comment by nilsreiter** [comment]
I'm afraid I cannot really package javafx into the jar, because it's os-dependent (and I really want to avoid having different packages for different os). The main reason for the JavaFX dependency is that the file dialogs look much more natural. If there is another way to achieve that, I'll be happy to remove JavaFX.

**Comment by andreasvc** [comment]
That's what I thought. I agree the file dialogs look better. Installation is now potentially a bit more difficult, but with clear README instructions it's not a problem. I can make a first version if you like.
