### ISSUE TITLE
Error with QuaDramA/TEI Import on recent GerDraCor release

### ISSUE THREAD

**Issue by pagelj** [nilsreiter/CorefAnnotator#219]
The *QuaDramA/TEI* Import function doesn't work for the current GerDraCor Release (tested with state at https://github.com/dracor-org/gerdracor/tree/5c02a5b7424331b1909ed49e3eddae7651374641)

Error Log:
```
14:14:17.585 done ERROR de.unistuttgart.ims.coref.annotator.Annotator - catching
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_222]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_222]
        at javax.swing.SwingWorker.get(SwingWorker.java:602) ~[?:1.8.0_222]
        at de.unistuttgart.ims.coref.annotator.worker.JCasLoader.done(JCasLoader.java:146) [CorefAnnotator-1.9.4-full.jar:1.9.4]
        at javax.swing.SwingWorker$5.run(SwingWorker.java:737) [?:1.8.0_222]
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832) [?:1.8.0_222]
        at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) [?:1.8.0_222]
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842) [?:1.8.0_222]
        at javax.swing.Timer.fireActionPerformed(Timer.java:313) [?:1.8.0_222]
        at javax.swing.Timer$DoPostEvent.run(Timer.java:245) [?:1.8.0_222]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_222]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_222]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_222]
        at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_222]
        at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_222]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_222]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_222]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_222]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_222]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_222]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_222]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_222]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
        at de.unistuttgart.ims.coref.annotator.plugin.quadrama.tei.TeiReader.lambda$getNext$6(TeiReader.java:127) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at de.unistuttgart.ims.uima.io.xml.GenericXmlReader.applyRule(GenericXmlReader.java:179) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at de.unistuttgart.ims.uima.io.xml.GenericXmlReader.read(GenericXmlReader.java:101) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at de.unistuttgart.ims.coref.annotator.plugin.quadrama.tei.TeiReader.getNext(TeiReader.java:134) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:140) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at de.unistuttgart.ims.coref.annotator.worker.JCasLoader.readFile(JCasLoader.java:126) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at de.unistuttgart.ims.coref.annotator.worker.JCasLoader.doInBackground(JCasLoader.java:139) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at de.unistuttgart.ims.coref.annotator.worker.JCasLoader.doInBackground(JCasLoader.java:33) ~[CorefAnnotator-1.9.4-full.jar:1.9.4]
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295) ~[?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
        at javax.swing.SwingWorker.run(SwingWorker.java:334) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]

```

**Comment by pagelj** [comment]
Tested with files https://github.com/dracor-org/gerdracor/blob/5c02a5b7424331b1909ed49e3eddae7651374641/tei/goethe-egmont.xml and https://github.com/dracor-org/gerdracor/blob/5c02a5b7424331b1909ed49e3eddae7651374641/tei/schiller-die-piccolomini.xml
