### ISSUE TITLE
Unable to start CorefAnnotator 1.12.0 with Java 8

### ISSUE THREAD

**Issue by pagelj** [nilsreiter/CorefAnnotator#265]
```
$ java -jar CorefAnnotator-1.12.0-full.jar
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.awt.Toolkit.getMenuShortcutKeyMaskEx()I
	at de.unistuttgart.ims.coref.annotator.action.ExitAction.<init>(ExitAction.java:21)
	at de.unistuttgart.ims.coref.annotator.Annotator.<init>(Annotator.java:81)
	at de.unistuttgart.ims.coref.annotator.Annotator$1.run(Annotator.java:102)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
```
$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
It is working with Java 13

**Comment by nilsreiter** [comment]
Do we really need it to work with Java 8?

**Comment by pagelj** [comment]
> Do we really need it to work with Java 8?

Probably not, it would just be more comfortable for me when working on the office computer, but I can do without it.

**Comment by andreasvc** [comment]
Just ran into this issue as well. But this time, `apt-get install openjdk-11-jdk openjdk-11-jre` solved everything without hassle (compared to #174).
