### ISSUE TITLE
NullPointerException when loading file

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#64]
[This file](https://github.com/nilsreiter/CorefAnnotator/files/1789299/Rowlandson_Tanja.xmi.zip)  doesn't load. Stacktrace:
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at javax.swing.SwingWorker.get(SwingWorker.java:602) ~[?:1.8.0_112]
	at de.unistuttgart.ims.coref.annotator.worker.CoreferenceModelLoader.done(CoreferenceModelLoader.java:61) [classes/:?]
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737) [?:1.8.0_112]
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832) [?:1.8.0_112]
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) [?:1.8.0_112]
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842) [?:1.8.0_112]
	at javax.swing.Timer.fireActionPerformed(Timer.java:313) [?:1.8.0_112]
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245) [?:1.8.0_112]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_112]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_112]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_112]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_112]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_112]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_112]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_112]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at de.unistuttgart.ims.coref.annotator.CoreferenceModel.addTo(CoreferenceModel.java:170) ~[classes/:?]
	at de.unistuttgart.ims.coref.annotator.worker.CoreferenceModelLoader.doInBackground(CoreferenceModelLoader.java:49) ~[classes/:?]
	at de.unistuttgart.ims.coref.annotator.worker.CoreferenceModelLoader.doInBackground(CoreferenceModelLoader.java:1) ~[classes/:?]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at javax.swing.SwingWorker.run(SwingWorker.java:334) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_112]
```

**Comment by nilsreiter** [comment]
It's an entity group.
